name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        # Use `npm install` when package-lock.json is not present in the repository.
        # `npm ci` requires a lockfile; CI will fail with EUSAGE if no lockfile exists.
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --prefer-offline
          fi

      - name: Build package
        run: npm run build

      - name: Publish to npm
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}